package Fachada;

import DAO.DAOException;
import DAO.MiembroCuerpoTecnicoDAO;
import java.sql.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import FactoryMethod.FactoriaIntegrantes;
import FactoryMethod.IntegrantePlantilla;

/**
 * Clase para que el directivo pueda modificar un miembro del cuerpo tecnico
 *
 * @author Javier y Christian
 */
public class ModificarMiembroCT extends javax.swing.JFrame {

    /**
     * Variable para saber el equipo al que pertenece el usuario registrado
     */
    private final int id_equipo;
    /**
     * DNI del usuario registrado
     */
    private final String DNI;

    /**
     * Constructor
     *
     * @param id_equipo
     * @param DNI
     */
    public ModificarMiembroCT(int id_equipo, String DNI) {
        this.id_equipo = id_equipo;
        this.DNI = DNI;
        initComponents();
        if (id_equipo == 1) {
            setIconImage(new ImageIcon(getClass().getResource("/imagen/lakers.jpg")).getImage());
        }
        if (id_equipo == 2) {
            setIconImage(new ImageIcon(getClass().getResource("/imagen/clippers.jpg")).getImage());
        }
        if (id_equipo == 3) {
            setIconImage(new ImageIcon(getClass().getResource("/imagen/nets.jpg")).getImage());
        }
        if (id_equipo == 4) {
            setIconImage(new ImageIcon(getClass().getResource("/imagen/bucks.jpg")).getImage());
        }
        if (id_equipo == 5) {
            setIconImage(new ImageIcon(getClass().getResource("/imagen/celtics.jpg")).getImage());
        }
        if (id_equipo == 6) {
            setIconImage(new ImageIcon(getClass().getResource("/imagen/bulls.jpg")).getImage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        DNITxt = new javax.swing.JTextField();
        SalarioButton = new javax.swing.JButton();
        SalarioTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        fechaButon = new javax.swing.JButton();
        FcontratoCombo = new javax.swing.JComboBox<>();
        VolverButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel6.setText("Introduzca el DNI del jugador que desea modificar");

        jLabel2.setText("Salario");

        SalarioButton.setText("Modificar salario");
        SalarioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalarioButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Fecha fin de contrato");

        fechaButon.setText("Modificar fecha fin de contrato");
        fechaButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechaButonActionPerformed(evt);
            }
        });

        FcontratoCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030" }));
        FcontratoCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FcontratoComboActionPerformed(evt);
            }
        });

        VolverButton.setText("Volver");
        VolverButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(VolverButton)
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DNITxt, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(64, 64, 64))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FcontratoCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SalarioTxt, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fechaButon)
                            .addComponent(SalarioButton))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(VolverButton))
                .addGap(18, 18, 18)
                .addComponent(DNITxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(SalarioButton))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(SalarioTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(FcontratoCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(fechaButon))
                .addContainerGap(145, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Botón para modificar la fecha de finzalicion de contrato del miembro del
     * cuerpo tecnico
     *
     * @param evt
     */
    private void fechaButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechaButonActionPerformed

        FactoriaIntegrantes factoria = new FactoriaIntegrantes();
        IntegrantePlantilla integrante = factoria.getIntegrantePlantilla(1);
        MiembroCuerpoTecnicoDAO dao = (MiembroCuerpoTecnicoDAO) integrante.crearIntegrantePostgreSQL();

        try {

            if (id_equipo == dao.obtenerIDEquipo("\'" + DNITxt.getText() + "\'")) {

                dao.modificarF((new Date(Integer.parseInt(FcontratoCombo.getSelectedItem().toString()) - 1900, 5, 30)), DNITxt.getText());
                JOptionPane.showMessageDialog(null, "Fecha fin de contrato modificada correctamente");
            } else {
                JOptionPane.showMessageDialog(null, "Este DNI no pertenece a su equipo");
            }

        } catch (DAOException ex) {
            System.out.println(ex.getMessage());
            JOptionPane.showMessageDialog(null, "Error al modificar");
        }
    }//GEN-LAST:event_fechaButonActionPerformed

    private void FcontratoComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FcontratoComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FcontratoComboActionPerformed
    /**
     * Botón para modificar el salario del miembro del cuerpo tecnico
     *
     * @param evt
     */
    private void SalarioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalarioButtonActionPerformed

        FactoriaIntegrantes factoria = new FactoriaIntegrantes();
        IntegrantePlantilla integrante = factoria.getIntegrantePlantilla(1);
        MiembroCuerpoTecnicoDAO dao = (MiembroCuerpoTecnicoDAO) integrante.crearIntegrantePostgreSQL();

        try {

            if (id_equipo == dao.obtenerIDEquipo("\'" + DNITxt.getText() + "\'")) {

                dao.modificar(Integer.parseInt(SalarioTxt.getText()), DNITxt.getText());
                JOptionPane.showMessageDialog(null, "Salario modificado correctamente");
            } else {
                JOptionPane.showMessageDialog(null, "Este DNI no pertenece a su equipo");
            }

        } catch (DAOException ex) {
            System.out.println(ex.getMessage());
            JOptionPane.showMessageDialog(null, "Error al modificar");
        }
    }//GEN-LAST:event_SalarioButtonActionPerformed
    /**
     * Boton para volver a la interfaz anterior
     *
     * @param evt
     */
    private void VolverButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverButtonActionPerformed
        FachadaIntegrante de = new FachadaIntegrante(id_equipo, DNI);
        this.setVisible(false);
        de.setVisible(true);
    }//GEN-LAST:event_VolverButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarMiembroCT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new ModificarMiembroCT(0, "").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DNITxt;
    private javax.swing.JComboBox<String> FcontratoCombo;
    private javax.swing.JButton SalarioButton;
    private javax.swing.JTextField SalarioTxt;
    private javax.swing.JButton VolverButton;
    private javax.swing.JButton fechaButon;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
