package Fachada;

import DAO.DAO;
import DAO.DAOException;
import Modelos.MiembroCuerpoTecnico;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import FactoryMethod.FactoriaIntegrantes;
import FactoryMethod.IntegrantePlantilla;

/**
 * Clase para que el directivo pueda dar de alta un miembro del cuerpo tecnico
 *
 * @author Javier y Christian
 */
public class AltaMiembroCT extends javax.swing.JFrame {

    /**
     * Variable para saber el equipo al que pertenece el usuario registrado
     */
    private final int id_equipo;
    /**
     * DNI del usuario registrado
     */
    private final String DNI;

    /**
     * Constructor
     *
     * @param id_equipo
     * @param DNI
     */
    public AltaMiembroCT(int id_equipo, String DNI) {
        this.id_equipo = id_equipo;
        this.DNI = DNI;
        initComponents();
        if (id_equipo == 1) {
            setIconImage(new ImageIcon(getClass().getResource("/imagen/lakers.jpg")).getImage());
        }
        if (id_equipo == 2) {
            setIconImage(new ImageIcon(getClass().getResource("/imagen/clippers.jpg")).getImage());
        }
        if (id_equipo == 3) {
            setIconImage(new ImageIcon(getClass().getResource("/imagen/nets.jpg")).getImage());
        }
        if (id_equipo == 4) {
            setIconImage(new ImageIcon(getClass().getResource("/imagen/bucks.jpg")).getImage());
        }
        if (id_equipo == 5) {
            setIconImage(new ImageIcon(getClass().getResource("/imagen/celtics.jpg")).getImage());
        }
        if (id_equipo == 6) {
            setIconImage(new ImageIcon(getClass().getResource("/imagen/bulls.jpg")).getImage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        FcontratoCombo = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        nacionalidadCombo = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        ApellidosTxt = new javax.swing.JTextField();
        NombreTxt = new javax.swing.JTextField();
        salarioTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        AceptarButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        mailTxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        DNITxt = new javax.swing.JTextField();
        puestoCombo = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        tacticaFavoritaCombo = new javax.swing.JComboBox<>();
        contraseñaField = new javax.swing.JPasswordField();
        jLabel12 = new javax.swing.JLabel();
        VolverButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel6.setText("Nacionalidad");

        FcontratoCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030" }));
        FcontratoCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FcontratoComboActionPerformed(evt);
            }
        });

        jLabel7.setText("Puesto");

        nacionalidadCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Argentina", "Española", "Estadounidense", "Francesa", "Italiana", " " }));
        nacionalidadCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nacionalidadComboActionPerformed(evt);
            }
        });

        jLabel8.setText("Tactica Favorita");

        ApellidosTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApellidosTxtActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre");

        jLabel2.setText("Apellidos");

        jLabel3.setText("DNI");

        AceptarButton.setText("Aceptar");
        AceptarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("Fecha fin contrato");

        jLabel9.setText("Mail");

        puestoCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Entrenador", "Asistente", "Preparador físico", "Médico", "Fisioterapeuta" }));
        puestoCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puestoComboActionPerformed(evt);
            }
        });

        jLabel5.setText("Salario");

        tacticaFavoritaCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Defensa en zona", "Pick and roll", "Triple", "Small ball", "Defensa al hombre", "Otras" }));
        tacticaFavoritaCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tacticaFavoritaComboActionPerformed(evt);
            }
        });

        jLabel12.setText("Contraseña");

        VolverButton.setText("Volver");
        VolverButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(VolverButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel7))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel12)))
                            .addComponent(jLabel3))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(puestoCombo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(salarioTxt, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NombreTxt, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ApellidosTxt, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nacionalidadCombo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(FcontratoCombo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mailTxt, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tacticaFavoritaCombo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DNITxt, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(contraseñaField, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(83, 83, 83))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AceptarButton)
                .addGap(163, 163, 163))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(NombreTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VolverButton))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ApellidosTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(DNITxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(FcontratoCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nacionalidadCombo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(puestoCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(salarioTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(mailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tacticaFavoritaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(contraseñaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addComponent(AceptarButton)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FcontratoComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FcontratoComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FcontratoComboActionPerformed

    private void nacionalidadComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nacionalidadComboActionPerformed

    }//GEN-LAST:event_nacionalidadComboActionPerformed
    /**
     * Botón para ejecutar el alta del miembro del cuerpo tecnico
     *
     * @param evt
     */
    private void AceptarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarButtonActionPerformed
        boolean insertadoCorrectamente = false;

        FactoriaIntegrantes factoria = new FactoriaIntegrantes();
        IntegrantePlantilla integrante = factoria.getIntegrantePlantilla(1);
        DAO dao = integrante.crearIntegrantePostgreSQL();

        MiembroCuerpoTecnico m1 = new MiembroCuerpoTecnico(NombreTxt.getText(), ApellidosTxt.getText(), puestoCombo.getSelectedItem().toString(),
                new Date(Integer.parseInt(FcontratoCombo.getSelectedItem().toString()) - 1900, 5, 30), nacionalidadCombo.getSelectedItem().toString(),
                Integer.parseInt(salarioTxt.getText()), tacticaFavoritaCombo.getSelectedItem().toString(), id_equipo, mailTxt.getText(), contraseñaField.getText());

        m1.setDNI(DNITxt.getText());

        try {
            dao.insertar(m1);
            insertadoCorrectamente = true;

        } catch (DAOException ex) {
            System.out.println(ex.getMessage());
            JOptionPane.showMessageDialog(null, "Error al dar de alta");
        }
        if (insertadoCorrectamente) {
            JOptionPane.showMessageDialog(null, "Miembro CT dado de alta correctamente");
            this.setDefaultCloseOperation(EXIT_ON_CLOSE);
            this.setVisible(true);
        }

    }//GEN-LAST:event_AceptarButtonActionPerformed

    private void puestoComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puestoComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_puestoComboActionPerformed

    private void tacticaFavoritaComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tacticaFavoritaComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tacticaFavoritaComboActionPerformed

    private void ApellidosTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApellidosTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ApellidosTxtActionPerformed
    /**
     * Boton para volver a la interfaz anterior
     *
     * @param evt
     */
    private void VolverButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverButtonActionPerformed
        FachadaIntegrante de = new FachadaIntegrante(id_equipo, DNI);
        this.setVisible(false);
        de.setVisible(true);
    }//GEN-LAST:event_VolverButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AltaMiembroCT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new AltaMiembroCT(0, "").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AceptarButton;
    private javax.swing.JTextField ApellidosTxt;
    private javax.swing.JTextField DNITxt;
    private javax.swing.JComboBox<String> FcontratoCombo;
    private javax.swing.JTextField NombreTxt;
    private javax.swing.JButton VolverButton;
    private javax.swing.JPasswordField contraseñaField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField mailTxt;
    private javax.swing.JComboBox<String> nacionalidadCombo;
    private javax.swing.JComboBox<String> puestoCombo;
    private javax.swing.JTextField salarioTxt;
    private javax.swing.JComboBox<String> tacticaFavoritaCombo;
    // End of variables declaration//GEN-END:variables
}
