package Fachada;

import DAO.DAOException;
import DAO.JugadorDAO;
import Modelos.Jugador;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import FactoryMethod.FactoriaIntegrantes;
import FactoryMethod.IntegrantePlantilla;

/**
 * Clase para que el directivo pueda dar de alta un jugador
 *
 * @author Javier y Christian
 */
public class AltaJugador extends javax.swing.JFrame {

    /**
     * Variable para saber el equipo al que pertenece el usuario registrado
     */
    private final int id_equipo;
    /**
     * DNI del usuario registrado
     */
    private final String DNI;

    /**
     * Constructor
     *
     * @param id_equipo
     * @param DNI
     */
    public AltaJugador(int id_equipo, String DNI) {
        this.id_equipo = id_equipo;
        this.DNI = DNI;
        initComponents();
        if (id_equipo == 1) {
            setIconImage(new ImageIcon(getClass().getResource("/imagen/lakers.jpg")).getImage());
        }
        if (id_equipo == 2) {
            setIconImage(new ImageIcon(getClass().getResource("/imagen/clippers.jpg")).getImage());
        }
        if (id_equipo == 3) {
            setIconImage(new ImageIcon(getClass().getResource("/imagen/nets.jpg")).getImage());
        }
        if (id_equipo == 4) {
            setIconImage(new ImageIcon(getClass().getResource("/imagen/bucks.jpg")).getImage());
        }
        if (id_equipo == 5) {
            setIconImage(new ImageIcon(getClass().getResource("/imagen/celtics.jpg")).getImage());
        }
        if (id_equipo == 6) {
            setIconImage(new ImageIcon(getClass().getResource("/imagen/bulls.jpg")).getImage());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        contraseñaField = new javax.swing.JPasswordField();
        ApellidosTxt = new javax.swing.JTextField();
        NombreTxt = new javax.swing.JTextField();
        salarioTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        AceptarButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        nacionalidadCombo = new javax.swing.JComboBox<>();
        estadoCombo = new javax.swing.JComboBox<>();
        mailTxt = new javax.swing.JTextField();
        DNITxt = new javax.swing.JTextField();
        posicionCombo = new javax.swing.JComboBox<>();
        dorsalCombo = new javax.swing.JComboBox<>();
        FcontratoCombo = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        contraseñaField1 = new javax.swing.JPasswordField();
        VolverButton = new javax.swing.JButton();

        jLabel11.setText("Contraseña");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nombre");

        jLabel2.setText("Apellidos");

        jLabel3.setText("DNI");

        AceptarButton.setText("Aceptar");
        AceptarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("Fecha fin contrato");

        jLabel5.setText("Salario");

        jLabel6.setText("Nacionalidad");

        jLabel7.setText("Posición");

        jLabel8.setText("Dorsal");

        jLabel9.setText("Mail");

        jLabel10.setText("Estado");

        nacionalidadCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Argentina", "Española", "Estadounidense", "Francesa", "Italiana", " " }));
        nacionalidadCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nacionalidadComboActionPerformed(evt);
            }
        });

        estadoCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Cedido", "En propiedad" }));
        estadoCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadoComboActionPerformed(evt);
            }
        });

        posicionCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Base", "Escolta", "Alero", "Ala-Pívot", "Pívot" }));
        posicionCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posicionComboActionPerformed(evt);
            }
        });

        dorsalCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60", "61", "62", "63", "64", "65", "66", "67", "68", "69", "70", "71", "72", "73", "74", "75", "76", "77", "78", "79", "80", "81", "82", "83", "84", "85", "86", "87", "88", "89", "90", "91", "92", "93", "94", "95", "96", "97", "98", "99" }));
        dorsalCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dorsalComboActionPerformed(evt);
            }
        });

        FcontratoCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030" }));
        FcontratoCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FcontratoComboActionPerformed(evt);
            }
        });

        jLabel12.setText("Contraseña");

        contraseñaField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contraseñaField1ActionPerformed(evt);
            }
        });

        VolverButton.setText("Volver");
        VolverButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(VolverButton)
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)))
                    .addComponent(jLabel12))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(posicionCombo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dorsalCombo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(estadoCombo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(salarioTxt, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NombreTxt, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ApellidosTxt, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nacionalidadCombo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DNITxt, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mailTxt)
                    .addComponent(FcontratoCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(contraseñaField1))
                .addContainerGap(76, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AceptarButton)
                .addGap(170, 170, 170))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(NombreTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VolverButton))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ApellidosTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(DNITxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(FcontratoCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nacionalidadCombo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(posicionCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(salarioTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(estadoCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(mailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dorsalCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(contraseñaField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(AceptarButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Botón para ejecutar el alta del jugador
     *
     * @param evt
     */
    private void AceptarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarButtonActionPerformed
        boolean insertadoCorrectamente = false;
        FactoriaIntegrantes factoria = new FactoriaIntegrantes();
        IntegrantePlantilla integrante = factoria.getIntegrantePlantilla(0);
        JugadorDAO dao = (JugadorDAO) integrante.crearIntegrantePostgreSQL();

        Jugador j1 = new Jugador(Integer.parseInt(dorsalCombo.getSelectedItem().toString()), NombreTxt.getText(), ApellidosTxt.getText(), (int) (Math.random() * 25 + 5), (int) (Math.random() * 9 + 1), (int) (Math.random() * 9 + 1),
                new Date(Integer.parseInt(FcontratoCombo.getSelectedItem().toString()) - 1900, 6, 31),
                nacionalidadCombo.getSelectedItem().toString(), posicionCombo.getSelectedItem().toString(), Integer.parseInt(salarioTxt.getText()), estadoCombo.getSelectedItem().toString(),
                id_equipo, mailTxt.getText(), contraseñaField1.getText());

        j1.setDNI(DNITxt.getText());

        try {
            if (dao.obtenerNumeroJugadores(id_equipo) == 16) {
                JOptionPane.showMessageDialog(null, "No se puede dar de alta a ningun jugador al estar su plantilla con el numero maximo de jugadores (16)");
            } else {
                if (dao.obtenerDorsal(id_equipo, Integer.parseInt(dorsalCombo.getSelectedItem().toString())) == 1) {
                    JOptionPane.showMessageDialog(null, "Ya existe un jugador con ese dorsal");

                } else {
                    dao.insertar(j1);
                    insertadoCorrectamente = true;
                }

            }

        } catch (DAOException ex) {
            System.out.println(ex.getMessage());
            JOptionPane.showMessageDialog(null, "Error al dar de alta");
        }
        if (insertadoCorrectamente) {
            JOptionPane.showMessageDialog(null, "Jugador dado de alta correctamente");
            NombreTxt.setText("");
            ApellidosTxt.setText("");
            DNITxt.setText("");
            salarioTxt.setText("");
            mailTxt.setText("");
            contraseñaField.setText("");
            FcontratoCombo.setSelectedIndex(0);
            dorsalCombo.setSelectedIndex(0);
            posicionCombo.setSelectedIndex(0);
            nacionalidadCombo.setSelectedIndex(0);
            estadoCombo.setSelectedIndex(0);
            contraseñaField.setText("");

        }

    }//GEN-LAST:event_AceptarButtonActionPerformed

    private void nacionalidadComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nacionalidadComboActionPerformed
    }//GEN-LAST:event_nacionalidadComboActionPerformed

    private void estadoComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estadoComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estadoComboActionPerformed

    private void posicionComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posicionComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_posicionComboActionPerformed

    private void dorsalComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dorsalComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dorsalComboActionPerformed

    private void FcontratoComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FcontratoComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FcontratoComboActionPerformed

    private void contraseñaField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contraseñaField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contraseñaField1ActionPerformed
    /**
     * Boton para volver a la interfaz anterior
     *
     * @param evt
     */
    private void VolverButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverButtonActionPerformed
        FachadaIntegrante de = new FachadaIntegrante(id_equipo, DNI);
        this.setVisible(false);
        de.setVisible(true);
    }//GEN-LAST:event_VolverButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AltaJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new AltaJugador(0, "").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AceptarButton;
    private javax.swing.JTextField ApellidosTxt;
    private javax.swing.JTextField DNITxt;
    private javax.swing.JComboBox<String> FcontratoCombo;
    private javax.swing.JTextField NombreTxt;
    private javax.swing.JButton VolverButton;
    private javax.swing.JPasswordField contraseñaField;
    private javax.swing.JPasswordField contraseñaField1;
    private javax.swing.JComboBox<String> dorsalCombo;
    private javax.swing.JComboBox<String> estadoCombo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField mailTxt;
    private javax.swing.JComboBox<String> nacionalidadCombo;
    private javax.swing.JComboBox<String> posicionCombo;
    private javax.swing.JTextField salarioTxt;
    // End of variables declaration//GEN-END:variables

}
