package Interfaces;

import DAO.DAOException;
import java.sql.SQLException;
import javax.swing.ImageIcon;

/**
 * Clase para que los usuario tipo dueño puedan acceder a sus funciones
 *
 * @author Javier y Christian
 */
public class InterfazDueño extends javax.swing.JFrame {

    /**
     * DNI del usuario que esta visitando la interfaz
     */
    private final String DNI;
    /**
     * id del equipo del usuario que esta visitando la interfaz
     */
    private final String id_equipo;

    /**
     * Constructor
     *
     * @param id_equipo
     * @param DNI
     */
    public InterfazDueño(String id_equipo, String DNI) {
        this.id_equipo = id_equipo;
        this.DNI = DNI;
        initComponents();

        if ("1".equals(id_equipo)) {
            setIconImage(new ImageIcon(getClass().getResource("/imagen/lakers.jpg")).getImage());
        }
        if ("2".equals(id_equipo)) {
            setIconImage(new ImageIcon(getClass().getResource("/imagen/clippers.jpg")).getImage());
        }
        if ("3".equals(id_equipo)) {
            setIconImage(new ImageIcon(getClass().getResource("/imagen/nets.jpg")).getImage());
        }
        if ("4".equals(id_equipo)) {
            setIconImage(new ImageIcon(getClass().getResource("/imagen/bucks.jpg")).getImage());
        }
        if ("5".equals(id_equipo)) {
            setIconImage(new ImageIcon(getClass().getResource("/imagen/celtics.jpg")).getImage());
        }
        if ("6".equals(id_equipo)) {
            setIconImage(new ImageIcon(getClass().getResource("/imagen/bulls.jpg")).getImage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PlantillaButton = new javax.swing.JButton();
        ModificarButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        AltaButton = new javax.swing.JButton();
        BajaButton = new javax.swing.JButton();
        LideresButton = new javax.swing.JButton();
        ClasificacionButton = new javax.swing.JButton();
        CerrarButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PlantillaButton.setText("Consultar plantillas");
        PlantillaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlantillaButtonActionPerformed(evt);
            }
        });

        ModificarButton.setText("Modificar mis datos personales");
        ModificarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel1.setText("           DUEÑO");

        AltaButton.setText("Alta directivo");
        AltaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AltaButtonActionPerformed(evt);
            }
        });

        BajaButton.setText("Baja directivo");
        BajaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BajaButtonActionPerformed(evt);
            }
        });

        LideresButton.setText("Ver líderes de la liga");
        LideresButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LideresButtonActionPerformed(evt);
            }
        });

        ClasificacionButton.setText("Ver clasificación");
        ClasificacionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClasificacionButtonActionPerformed(evt);
            }
        });

        CerrarButton.setText("Cerrar Sesión");
        CerrarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CerrarButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BajaButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AltaButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ModificarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PlantillaButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ClasificacionButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LideresButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(210, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(CerrarButton)
                    .addComponent(jLabel1))
                .addGap(42, 42, 42)
                .addComponent(PlantillaButton)
                .addGap(18, 18, 18)
                .addComponent(ModificarButton)
                .addGap(18, 18, 18)
                .addComponent(AltaButton)
                .addGap(18, 18, 18)
                .addComponent(BajaButton)
                .addGap(18, 18, 18)
                .addComponent(LideresButton)
                .addGap(18, 18, 18)
                .addComponent(ClasificacionButton)
                .addContainerGap(131, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Boton para acceder a la interfaz de consulta de plantillas
     *
     * @param evt
     */
    private void PlantillaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlantillaButtonActionPerformed
        ConsultaPlantillas cp = new ConsultaPlantillas("Dueño", DNI, Integer.parseInt(id_equipo));
        this.setVisible(false);
        cp.setVisible(true);
    }//GEN-LAST:event_PlantillaButtonActionPerformed
    /**
     * Boton para acceder a la interfaz de modificar datos
     *
     * @param evt
     */
    private void ModificarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarButtonActionPerformed
        ModificarDatos mb = new ModificarDatos("Dueño", DNI, Integer.parseInt(id_equipo));
        this.setVisible(false);
        mb.setVisible(true);
    }//GEN-LAST:event_ModificarButtonActionPerformed
    /**
     * Boton para acceder a la interfaz de alta de directivos
     *
     * @param evt
     */
    private void AltaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AltaButtonActionPerformed
        AltaDirectivo at = new AltaDirectivo(id_equipo, DNI);
        this.setVisible(false);
        at.setVisible(true);
    }//GEN-LAST:event_AltaButtonActionPerformed
    /**
     * Boton para acceder a la interfaz de baja de directivos
     *
     * @param evt
     */
    private void BajaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BajaButtonActionPerformed
        BajaDirectivo bd = new BajaDirectivo(id_equipo, DNI);
        this.setVisible(false);
        bd.setVisible(true);
    }//GEN-LAST:event_BajaButtonActionPerformed
    /**
     * Boton para acceder a la interfaz de los lideres de la liga
     *
     * @param evt
     */
    private void LideresButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LideresButtonActionPerformed
        LideresLiga ll = new LideresLiga("Dueño", DNI, Integer.parseInt(id_equipo));
        this.setVisible(false);
        ll.setVisible(true);
    }//GEN-LAST:event_LideresButtonActionPerformed
    /**
     * Boton para acceder a la interfaz de la clasificación
     *
     * @param evt
     */
    private void ClasificacionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClasificacionButtonActionPerformed
        Clasificacion ll = new Clasificacion("Dueño", DNI, Integer.parseInt(id_equipo));
        this.setVisible(false);
        ll.setVisible(true);
    }//GEN-LAST:event_ClasificacionButtonActionPerformed
    /**
     * Boton para cerrar sesión
     *
     * @param evt
     */
    private void CerrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarButtonActionPerformed
        Login l;
        try {
            l = new Login();
            this.setVisible(false);
            l.setVisible(true);
        } catch (SQLException | DAOException ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_CerrarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazDueño.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new InterfazDueño("", "").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AltaButton;
    private javax.swing.JButton BajaButton;
    private javax.swing.JButton CerrarButton;
    private javax.swing.JButton ClasificacionButton;
    private javax.swing.JButton LideresButton;
    private javax.swing.JButton ModificarButton;
    private javax.swing.JButton PlantillaButton;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
